# Generated by Django 5.2.13 on 2026-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='member_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
